# Generated by Django 5.2.16 on 2026-08-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metagraph", "0014_retention_miner_block_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="metagraphdump",
            name="tempo",
            field=models.PositiveIntegerField(
                blank=True, help_text="Subnet tempo at dump time; NULL on legacy rows (pre-0015)", null=True
            ),
        ),
        migrations.CreateModel(
            name="ValidatorApyIngestState",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("last_snapshot_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "metagraph_validator_apy_ingest_state",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="validator_apy_ingest_state_singleton")
                ],
            },
        ),
        migrations.CreateModel(
            name="ValidatorApyEpoch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("subnet_id", models.PositiveIntegerField(help_text="netuid (plain value, no FK)")),
                ("epoch_block", models.PositiveBigIntegerField()),
                (
                    "epoch_ts",
                    models.DateTimeField(
                        blank=True, help_text="Block timestamp; NULL until the source block is timestamped", null=True
                    ),
                ),
                (
                    "alpha_stake",
                    models.DecimalField(decimal_places=0, help_text="Alpha stake in rao", max_digits=30),
                ),
                (
                    "alpha_dividends",
                    models.DecimalField(
                        decimal_places=0, help_text="Net alpha dividends this epoch in rao", max_digits=30
                    ),
                ),
                (
                    "total_stake",
                    models.DecimalField(decimal_places=0, help_text="Total stake in rao", max_digits=30),
                ),
                ("tempo", models.PositiveIntegerField()),
                ("apy_pct", models.FloatField()),
                (
                    "hotkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="apy_epochs", to="metagraph.hotkey"
                    ),
                ),
                (
                    "neuron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="apy_epochs", to="metagraph.neuron"
                    ),
                ),
            ],
            options={
                "db_table": "metagraph_validator_apy_epoch",
                "indexes": [
                    models.Index(fields=["subnet_id", "epoch_ts"], name="idx_vae_subnet_ts"),
                    models.Index(fields=["epoch_ts"], name="idx_vae_ts"),
                    models.Index(fields=["subnet_id", "neuron", "-epoch_block"], name="idx_vae_latest"),
                    models.Index(
                        condition=models.Q(("epoch_ts__isnull", True)), fields=["epoch_block"], name="idx_vae_null_ts"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subnet_id", "neuron", "epoch_block"), name="unique_validator_apy_epoch"
                    )
                ],
            },
        ),
        migrations.RunSQL(
            # Load-bearing: a fresh deploy must never interpret an absent
            # watermark as "scan the whole snapshot table". Seed to the
            # current maximum; the manual backfill covers everything below it.
            sql=(
                "INSERT INTO metagraph_validator_apy_ingest_state (id, last_snapshot_id) "
                "SELECT 1, COALESCE(MAX(id), 0) FROM metagraph_neuron_snapshot "
                "ON CONFLICT (id) DO NOTHING;"
            ),
            reverse_sql="DELETE FROM metagraph_validator_apy_ingest_state WHERE id = 1;",
        ),
    ]
